### ISSUE TITLE
HTTP Code 403 on activation

### ISSUE THREAD

**Issue by craig** [DropMorePackets/berghain#7]
Berghain / haproxy in the default config sends a 403 when it gets activated. It should probably be a 429 or something 3xx, so it does not get cached.

**Comment by fionera** [comment]
I took inspiration for this from Cloudflare since they are also doing this. You can change this behaviour by editing the HAProxy config here https://github.com/DropMorePackets/berghain/blob/master/examples/haproxy/haproxy.cfg#L38
